name: Match3_MacOS

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: brew update
    - run: brew install sdl2
    - run: brew install sdl2_ttf
    - run: brew postinstall sdl2
    - run: mkdir build && cd build && cmake ..
    - run: make -C build -j
      