name: Match3_MacOS_cppcheck

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: brew update
    - run: brew install cppcheck
    - run: cppcheck --enable=warning,performance,portability --error-exitcode=1 -v Source
      