name: Match3_Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt install build-essential cmake libsdl2-dev libsdl2-ttf-dev
    - run: mkdir build && cd build && cmake ..
    - run: make -C build -j
      