name: Match3_Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: mkdir build && cd build && cmake ..
    - run: dir D:/a/Match3/Match3/build
    - run: msbuild build/Match3.sln
      