name: Match3_MacOS_Test

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: brew install sdl2 sdl2_ttf
    - run: mkdir build && cd build && cmake ..
    - run: make -C build -j
