name: Match3_Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: mkdir build && cd build && cmake ..
    - run: make -C build -j
      