name: Match3_Linux_cppcheck

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt update
    - run: sudo apt install cppcheck
    - run: cppcheck --enable=warning,performance,portability --error-exitcode=1 -v Source
      